### ISSUE TITLE
Use Jenks Natural breaks as breaks?

### ISSUE THREAD

**Issue by RicardoRH96** [jschoeley/tricolore#22]
Hi all, I've got some data that I want to visualize using your package... However this data is count data on three variables.
The issue is one of my variables has a range between 1 and 3478 while the maximum value of the other two is ~200.
I have overcomed this previously by combining Jenks breaks with the "bivariate" package, however that package only works with 2 variables.
I'd like to use jenks breks instead of percentages to assign the scales.
Map for reference:
![image](https://github.com/jschoeley/tricolore/assets/87875949/14d3b2b4-dd2a-4971-81be-686274c496d4)

**Comment by jschoeley** [comment]
Hi Ricardo,

have you considered using the ternary centering option in Tricolore? Try `Tricolore(., center = NA)` (works best with continous colors).

![image](https://github.com/jschoeley/tricolore/assets/10901917/2d392201-8ab8-4898-94f7-6dc727ceb136)

This option is unique to tricolore and is intended to be used with highly unbalanced proportions. Instead of visualizing deviations from a perfectly balanced proportion (1/3 in each category) it visualizes deviations from a reference proportion. The technique is described here: https://www.jstor.org/stable/27032921

Note that tricolore won't visualize any magnitude information, e.g. (20, 40, 100) and (40, 80, 200) both map to composition (0.125, 0.250, and 0.625) and thus map to the same color.
